spring.application.name=backend

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/usuarios_db}
spring.datasource.username=${DB_USERNAME:chatbot}
spring.datasource.password=${DB_PASSWORD:dev}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}
